insert into franchise (id, name, description) values (1, 'matrix value-added schemas', 'Postdysenteric arthropathy, unspecified elbow');
insert into franchise (id, name, description) values (2, 'utilize back-end models', 'Benign neoplasm of other and unsp intrathoracic organs');
insert into franchise (id, name, description) values (3, 'leverage real-time partnerships', 'Unsp subluxation of right sternoclavicular joint, subs');
insert into franchise (id, name, description) values (4, 'innovate next-generation e-tailers', 'Vasculitis limited to the skin, unspecified');
insert into franchise (id, name, description) values (5, 'evolve seamless convergence', 'Unsp dislocation of unsp ulnohumeral joint, subs encntr');
insert into franchise (id, name, description) values (6, 'extend one-to-one bandwidth', 'Superficial foreign body, right foot, sequela');
insert into franchise (id, name, description) values (7, 'architect next-generation vortals', 'Driver of pk-up/van injured in clsn w pedl cyc nontraf, init');
insert into franchise (id, name, description) values (8, 'target turn-key niches', 'Other myositis, lower leg');
insert into franchise (id, name, description) values (9, 'seize 24/365 deliverables', 'Pathological fracture, left foot, subs for fx w malunion');
insert into franchise (id, name, description) values (10, 'engineer visionary supply-chains', 'Lens-induced iridocyclitis, bilateral');
